version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.20
    working_directory: ~/project

  node-executor:
    docker:
      - image: cimg/node:18.17
    working_directory: ~/project

  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project

commands:
  install_hadolint:
    description: "Install hadolint"
    steps:
      - run:
          name: Install Hadolint
          command: |
            curl -L -o /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x /usr/local/bin/hadolint

jobs:
  lint-dockerfile:
    executor: docker-executor
    steps:
      - checkout
      - install_hadolint
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Build and Push Backend Docker Image
          command: |
            chmod +x build_push_image_karsajobs.sh
            ./build_push_image_karsajobs.sh

  build-app-karsajobs-ui:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Build and Push Frontend Docker Image
          command: |
            chmod +x build_push_image_karsajobs_ui.sh
            ./build_push_image_karsajobs_ui.sh

workflows:
  version: 2
  ci-karsajobs:
    when:
      equal: [ "karsajobs", << pipeline.git.branch >> ]
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs

  ci-karsajobs-ui:
    when:
      equal: [ "karsajobs-ui", << pipeline.git.branch >> ]
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui
