version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            apk add --no-cache curl bash
            curl -L -o /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x /usr/local/bin/hadolint
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: Unit Test Backend
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Backend Image
          command: |
            docker build -t ghcr.io/teddy-harfa/karsajobs:latest .
            docker images | grep 'karsajobs'
            echo $CR_PAT | docker login ghcr.io -u teddy-harfa --password-stdin
            docker push ghcr.io/teddy-harfa/karsajobs:latest

  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Frontend Image
          command: |
            docker build -t ghcr.io/teddy-harfa/karsajobs-ui:latest .
            docker images | grep 'karsajobs'
            echo $CR_PAT | docker login ghcr.io -u teddy-harfa --password-stdin
            docker push ghcr.io/teddy-harfa/karsajobs-ui:latest

workflows:
  version: 2

  lint-test-and-build-karsajobs:
    jobs:
      - test-app:
          filters:
            branches:
              only: karsajobs
      - lint-dockerfile:
          filters:
            branches:
              only: karsajobs
      - build-app-karsajobs:
          requires:
            - test-app
            - lint-dockerfile
          filters:
            branches:
              only: karsajobs

  lint-and-build-karsajobs-ui:
    jobs:
      - lint-dockerfile:
          filters:
            branches:
              only: karsajobs-ui
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
          filters:
            branches:
              only: karsajobs-ui
